name: Deploy to Linode

on:
  push:
    branches: [dev-stage2]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install -g pm2
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
    - name: List files in workspace
      run: |
        ls -la
        ls -la src/
        ls -la tests/
        find . -name "*.js" -type f | head -20
    - name: Upload backend code
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: |
          src/
          tests/
          .sequelizerc
          jest.config.js
          migrate.js
          package.json
          package-lock.json
        target: "${{ secrets.SERVER_DIR }}"
        debug: true
        rm: false
    - name: Check workspace contents
      run: ls -R
    - name: Restart backend (via SSH)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          export PATH=$PATH:/root/.nvm/versions/node/v18.20.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
          cd ${{ secrets.SERVER_DIR }}
          npm install
          node .\migrate.js
          pm2 restart server-backend || pm2 start src/index.js --name server-backend
